spring:
  application:
    name: ms-provider
  datasource:
    name: ds-ms
    url: jdbc:mysql://127.0.0.1:3306/ms
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      max-file-size: 600Mb
      max-request-size: 600Mb

server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
    instance-id: http://localhost:8762/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.train.model

app:
  max:
    size: 524288000
  ftp:
    dir: file
    url:  10.1.36.201
    port: 8888
    username: test
    password: test
    domain: http://10.1.36.201:8888/