spring:
  application:
    name: ms-provider

server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
    instance-id: http://localhost:8762/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/