spring:
  application:
    name: ms-spider

server:
  port: 8763

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true #启用 feign的hystrix

app:
  provider: ms-provider